# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: impurity_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16impurity_service.proto\x12\x08impurity\"\"\n\x12ProcessDataRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"%\n\x13ProcessDataResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2]\n\rComputingUnit\x12L\n\x0bProcessData\x12\x1c.impurity.ProcessDataRequest\x1a\x1d.impurity.ProcessDataResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'impurity_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROCESSDATAREQUEST']._serialized_start=36
  _globals['_PROCESSDATAREQUEST']._serialized_end=70
  _globals['_PROCESSDATARESPONSE']._serialized_start=72
  _globals['_PROCESSDATARESPONSE']._serialized_end=109
  _globals['_COMPUTINGUNIT']._serialized_start=111
  _globals['_COMPUTINGUNIT']._serialized_end=204
# @@protoc_insertion_point(module_scope)
