
services:      
  redis:
    image: "redis:alpine"
    container_name: rt-cvision-redis
    restart: "always"
    volumes:
      - cache:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - internal

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: rt-cvision-zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - internal

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: rt-cvision-kafka
    restart: always
    networks: 
      - internal
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100

  rt-cvision:
    image: tannousgeagea/rtcvision:v1.0.1
    container_name: rt-cvision-core
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ros_version: ${ros_version}
        ros_distro: ${ros_distro}
        user: ${user}
        userid: ${userid}
        group: ${group}
        groupid: ${groupid}
        CUDA_VERSION: ${CUDA_VERSION}
    networks: 
      - internal
    ports:
      - ${INET_HTTP_SERVER_PORT}:${INET_HTTP_SERVER_PORT}
      - ${DJANGO_ADMIN_PORT}:${DJANGO_ADMIN_PORT}
      - ${CONFIGURE_API_PORT}:${CONFIGURE_API_PORT}
    restart: unless-stopped
    depends_on:
      - redis
      - kafka
      - ros2
    volumes:
      - ./:/home/$user/src
      # - data:/home/$user/src/rt_cvision/sqlite
      - media:/media/$user/rt_cvision
    user: ${user}
    environment:
      ros_version: ros2
      ros_distro: humble
      user: appuser
      userid: 1000
      group: appuser
      groupid: 1000
      CUDA_VERSION: 12.5.1-cudnn-runtime-ubuntu22.04
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ros2:
    image: tannousgeagea/ros2:humble-desktop
    container_name: ros2_bag_player
    stdin_open: true
    tty: true
    networks: 
      - internal
    volumes:
      - /home/wasteantadmin/Workspace/Datasets:/rosbags
    command: ["ros2", "bag", "play", "/rosbags/rosbag2_2025_03_03-12_15_43_0.db3", '--loop']

volumes:
  cache:
    driver: local
  media:
    driver: local
  data:
    driver: local

networks:
  internal: