version: '3.3'

services:
  # roscore
  roscore:
    image: ros:noetic-ros-core
    env_file: .env
    container_name: cvision-dl-ops-dev-roscore
    network_mode: host
    command: roscore
    restart: always
    ports:
      - "11312:11312"
      
  # redis
  redis:
    image: "redis:alpine"
    container_name: cvision-dl-ops-dev-redis
    restart: "always"
    ports:
      - "6379:6379"
      - "16379:16379"
    volumes:
    - cache:/data
    - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  # zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: cvision-dl-ops-dev-zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # kafka
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: cvision-dl-ops-dev-kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100

  # computing unit
  cvision-dl-ops:
    image: wasteant/wasteant:cvision-dl-ops-ubuntu.20.04-cuda.11.5.2
    container_name: cvision-dl-ops-dev-core
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: .
      args:
        user: ${user}
        userid: ${userid}
        group: ${group}
        groupid: ${groupid}
    network_mode: host
    env_file: .env
    restart: unless-stopped
    depends_on:
      - redis
      - kafka
      - roscore
    volumes:
      - ./src:/home/$user/src
      - ./data:/home/$user/data
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    user: ${user}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]




volumes:
  cache:
    driver: local