# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: visualizes_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18visualizes_service.proto\x12\nvizualizes\"\"\n\x12ProcessDataRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"%\n\x13ProcessDataResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2a\n\rComputingUnit\x12P\n\x0bProcessData\x12\x1e.vizualizes.ProcessDataRequest\x1a\x1f.vizualizes.ProcessDataResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'visualizes_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROCESSDATAREQUEST']._serialized_start=40
  _globals['_PROCESSDATAREQUEST']._serialized_end=74
  _globals['_PROCESSDATARESPONSE']._serialized_start=76
  _globals['_PROCESSDATARESPONSE']._serialized_end=113
  _globals['_COMPUTINGUNIT']._serialized_start=115
  _globals['_COMPUTINGUNIT']._serialized_end=212
# @@protoc_insertion_point(module_scope)
