# Generated by Django 4.2 on 2025-06-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_reader', '0003_image_height_image_width_imagetag_image_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetag',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagetag',
            name='source',
            field=models.CharField(choices=[('auto', 'Auto'), ('human', 'Human'), ('model', 'Model')], default='auto', max_length=50),
        ),
    ]
