"""
Django settings for rt_cvision project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3gzet0q4rek4_(vqil*yfmho%96&cf0a7r6ei7+69%meoz&cgj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [os.getenv("ALLOWED_HOST", "0.0.0.0"), os.getenv("Systenname", 'localhost')]


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'configure',
    'users',
    'tenants',
    'metadata',
    'data_reader',
    'impurity',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rt_cvision.urls'
AUTH_USER_MODEL = "users.CustomUser"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rt_cvision.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DATABASE_ENGINE', "django.db.backends.sqlite3"),
        'NAME': os.environ.get('DATABASE_NAME') if not 'sqlite3' in os.environ.get('DATABASE_ENGINE', '') else BASE_DIR / 'db.sqlite3',
        'USER': os.environ.get('DATABASE_USER'),
        'PASSWORD': os.environ.get('DATABASE_PASSWD'),
        'HOST': os.environ.get('DATABASE_HOST'),
        'PORT': os.environ.get('DATABASE_PORT')

    },
    'config': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'sqlite/db.sqlite3',
    }
}

DATABASE_ROUTERS = ["rt_cvision.router.ConfigRouter"]

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'sqlite/db.sqlite3',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
MEDIA_URL = "media/"
MEDIA_ROOT = "/media/appuser/rt_cvision/experiments"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

UNFOLD = {
    "SITE_HEADER": _("RTCVision"),
    "SITE_TITLE": _("RTCVision"),
    "SITE_SYMBOL": "visibility",
    # "SITE_LOGO": {
    #     "light": lambda r: static("wa-logo-green.png"),  # light mode
    #     "dark": lambda r: static("wa-logo-white.png"),  # dark mode
    # },
    # "LOGIN": {
    #     "image": lambda r: static("login-bg.png"),
    #     # "redirect_after": lambda r: reverse_lazy("admin:APP_MODEL_changelist"),
    # },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("Navigation"),
                "items": [
                    {
                        "title": _("All Apps"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ]
            },
            {
                "title": _("Tenants"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Tenant"),
                        "icon": 'tenancy',
                        "link": reverse_lazy(
                            "admin:tenants_tenant_changelist"
                        ),
                    },
                    {
                        "title": _("Entity"),
                        "icon": 'fingerprint',
                        "link": reverse_lazy(
                            "admin:tenants_entitytype_changelist"
                        ),
                    },
                    {
                        "title": _("Tenant Entity"),
                        "icon": 'type_specimen',
                        "link": reverse_lazy(
                            "admin:tenants_plantentity_changelist"
                        ),
                    },
                    {
                        "title": _("SensorBoxes"),
                        "icon": 'sensors',
                        "link": reverse_lazy(
                            "admin:tenants_sensorbox_changelist"
                        ),
                    },
                ]
            },
            {
                "title": _("Users & Groups"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "person",
                        "link": reverse_lazy(
                            "admin:users_customuser_changelist"
                            ),
                    },
                    {
                        "title": _("Groups"),
                        "icon": "group",
                        "link": reverse_lazy(
                            "admin:auth_group_changelist"
                            ),
                    }
                ],
            },
            {
                "title": _("Configuration"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Value Types"),
                        "icon": "type_specimen",
                        "link": reverse_lazy(
                            "admin:configure_valuetype_changelist"
                        ),
                    },
                    {
                        "title": _("Input Types"),
                        "icon": "input",
                        "link": reverse_lazy(
                            "admin:configure_inputtype_changelist"
                        ),
                    },
                    {
                        "title": _("Configuration Fields"),
                        "icon": 'manufacturing',
                        "link": reverse_lazy(
                            "admin:configure_configfielddefinition_changelist"
                        ),
                    },
                    {
                        "title": _("Services"),
                        "icon": 'linked_services',
                        "link": reverse_lazy(
                            "admin:configure_service_changelist"
                        ),
                    },
                    {
                        "title": _("Service Parameters"),
                        "icon": 'settings',
                        "link": reverse_lazy(
                            "admin:configure_serviceparams_changelist"
                        ),
                    },
                    {
                        "title": _("Service Config Group"),
                        "icon": 'tab_group',
                        "link": reverse_lazy(
                            "admin:configure_serviceconfiggroup_changelist"
                        ),
                    },
                    {
                        "title": _("App config"),
                        "icon": 'settings',
                        "link": reverse_lazy(
                            "admin:configure_appconfig_changelist"
                        ),
                    },
                    {
                        "title": _("Data Sources"),
                        "icon": 'frame_source',
                        "link": reverse_lazy(
                            "admin:configure_datasource_changelist"
                        ),
                    },
                    {
                        "title": _("Data Aquicistion Config"),
                        "icon": 'topic',
                        "link": reverse_lazy(
                            "admin:configure_dataacquisitionconfig_changelist"
                        ),
                    },
                ]
            },
            {
                "title": _("Metadata"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Language"),
                        "icon": "language",
                        "link": reverse_lazy(
                            "admin:metadata_language_changelist"
                        ),
                    },
                    {
                        "title": _("Tag Groups"),
                        "icon": "language",
                        "link": reverse_lazy(
                            "admin:metadata_taggroup_changelist"
                        ),
                    },
                    {
                        "title": _("Tags"),
                        "icon": "language",
                        "link": reverse_lazy(
                            "admin:metadata_tag_changelist"
                        ),
                    },
                ]
            },
            {
                "title": _("Data"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Images"),
                        "icon": 'image',
                        "link": reverse_lazy(
                            "admin:data_reader_image_changelist"
                        ),
                    },
                ]
            },
            {
                "title": _("Impurities"),
                "collapsible": True,
                "items": [
                                        {
                        "title": _("Impurity Tasks"),
                        "icon": 'add_task',
                        "link": reverse_lazy(
                            "admin:impurity_impuritytask_changelist"
                        ),
                    },
                    {
                        "title": _("Impurity"),
                        "icon": 'comedy_mask',
                        "link": reverse_lazy(
                            "admin:impurity_impurity_changelist"
                        ),
                    },
                ]
            },
        ],
    },
}
