# Generated by Django 4.2 on 2024-08-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceparams',
            name='value',
            field=models.JSONField(null=True),
        ),
    ]
