# Generated by Django 4.2 on 2024-08-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0002_alter_serviceparams_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceparams',
            name='value',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
