# Generated by Django 4.2 on 2025-02-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0003_alter_serviceparams_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_configured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
