# Generated by Django 4.2 on 2025-05-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0003_alter_serviceparams_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceparams',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if the parameter is currently active.'),
        ),
    ]
