# Generated by Django 4.2 on 2025-02-07 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0004_appconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('interface', models.CharField(choices=[('ros2', 'ROS2 Topic'), ('mqtt', 'MQTT Topic'), ('api', 'REST API Endpoint'), ('websocket', 'WebSocket Feed'), ('file', 'File Source')], max_length=50)),
                ('is_available', models.BooleanField(default=False)),
                ('last_detected', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataAcquisitionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configure.datasource')),
            ],
        ),
    ]
