# Generated by Django 4.2 on 2025-02-25 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0005_datasource_dataacquisitionconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Input Type',
                'verbose_name_plural': 'Input Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ValueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Value Type',
                'verbose_name_plural': 'Value Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceConfigGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('meta_info', models.JSONField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='config_groups', to='configure.service')),
            ],
            options={
                'verbose_name': 'Service Configuration Group',
                'verbose_name_plural': 'Service Configuration Groups',
                'db_table': 'service_config_group',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ConfigFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(help_text="A unique identifier for the field (e.g., 'auth-mode').", max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('default_value', models.JSONField(blank=True, help_text='Default value for the field.', null=True)),
                ('validation', models.JSONField(blank=True, help_text="Validation rules (e.g., {'required': True, 'min': 1, 'max': 168}).", null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('meta_info', models.JSONField(blank=True, null=True)),
                ('input_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configure.inputtype')),
                ('value_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configure.valuetype')),
            ],
            options={
                'verbose_name': 'Configuration Field Definition',
                'verbose_name_plural': 'Configuration Field Definitions',
                'db_table': 'config_field_definition',
                'unique_together': {('field_id',)},
            },
        ),
        migrations.CreateModel(
            name='ServiceConfigFieldInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, help_text='The value for this field instance. If not set, the default from the definition may be used.', null=True)),
                ('meta_info', models.JSONField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('definition', models.ForeignKey(help_text='Reference to the shared field definition.', on_delete=django.db.models.deletion.PROTECT, to='configure.configfielddefinition')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fields', to='configure.serviceconfiggroup')),
            ],
            options={
                'verbose_name': 'Service Configuration Field Instance',
                'verbose_name_plural': 'Service Configuration Field Instances',
                'db_table': 'service_config_field_instance',
                'ordering': ['order'],
                'unique_together': {('group', 'definition')},
            },
        ),
    ]
