# Generated by Django 4.2 on 2025-03-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0006_inputtype_valuetype_serviceconfiggroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configfielddefinition',
            name='options',
            field=models.JSONField(blank=True, help_text="For select or multiselect input types, an array of available options. Each option can be an object with keys like 'id' and 'label'.", null=True),
        ),
    ]
