# Generated by Django 4.2 on 2025-06-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0007_configfielddefinition_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='configfielddefinition',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if the parameter is currently active.'),
        ),
        migrations.AddField(
            model_name='serviceconfigfieldinstance',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if the parameter is currently active.'),
        ),
        migrations.AddField(
            model_name='serviceconfiggroup',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if the parameter is currently active.'),
        ),
    ]
