# Generated by Django 4.2 on 2025-06-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0008_configfielddefinition_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconfigfieldinstance',
            name='options',
            field=models.JSONField(blank=True, help_text='Service-specific options for select/multiselect inputs. Overrides the default definition if set.', null=True),
        ),
    ]
