# Generated by Django 4.2 on 2024-12-11 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_reader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_uid', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('tracker_id', models.IntegerField(blank=True, null=True)),
                ('confidence_score', models.FloatField()),
                ('class_id', models.IntegerField()),
                ('object_coordinates', models.JSONField(blank=True, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='image', to='data_reader.image')),
            ],
            options={
                'verbose_name_plural': 'Impurities',
                'db_table': 'impurity',
            },
        ),
    ]
