# Generated by Django 4.2 on 2024-12-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impurity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='impurity',
            name='object_length',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
