# Generated by Django 4.2 on 2024-12-14 23:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('impurity', '0002_impurity_object_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impurity',
            name='tracker_id',
        ),
        migrations.AddField(
            model_name='impurity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
