# Generated by Django 4.2 on 2024-12-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impurity', '0003_remove_impurity_tracker_id_impurity_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='impurity',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
