# Generated by Django 4.2 on 2024-12-16 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impurity', '0005_impurity_sensorbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impurity',
            name='sensorbox',
        ),
    ]
