# Generated by Django 4.2 on 2025-02-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impurity', '0006_remove_impurity_sensorbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpurityTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Impurity Tasks',
                'db_table': 'impurity_task',
            },
        ),
    ]
