# Generated by Django 4.2 on 2025-02-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impurity', '0007_impuritytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='impuritytask',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
